name = "AdventOfCode2019"
uuid = "0c60ab8e-ae83-482c-abb2-b9c5f83a0e34"
authors = ["Alexander Seiler <seileralex@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
